<?php
//MENU PRINCIPAL
$botiga = "retbutiko";
$cistella = "a&#265;et-korbo";
$formulari = "mendilo";


//PAGINA: BOTIGA
$categoria = "Kategorio";
$preu_total = "Totala prezo";
$afegir_a_cistella = "Aldoni en la korbon";
$selecciona_una_categoria = "Elektu kategorion...";
$productes = "A&#265;eta&#309;oj";

$vols_afegir = "&#264;u vi volas aldoni";
$a_la_cistella = "en la korbon?";


//PAGINA: ACXETAJXOJN
$producte = "a&#265;eta&#309;o";
$quants = "Kvanto";
$euro_la_unitat = "Po e&#365;roj";
$quantitat_total_compra = "Entuta a&#265;eta&#309;o";

//no fiqueu codi HTML perque va dins d'un script JAVASCRIPT i no es pot
$vols_esborrar = "Cxu vi deziras forvisxi cxiujn acxetajxojn el via korbo";

$la_teua_cistella = "Via a&#265;et-korbo";
$descripcio_la_teua_cistella = "Kiam vi elektos diversajn a&#265;eta&#309ojn; el la retbutiko, ili tuj aperos tie &#265;i. Vi povas aldoni tiom da a&#265;eta&#309;ojn kiom vi deziras, poste vi ja povos ilin forvi&#349;i per la ru&#285;a kruco dekstre aperanta.</p><p>Se vi deziras mendi la a&#265;eta&#309;ojn kiuj trovi&#285;as en via a&#265;et-korbo, iru al mendilo kaj plenigu &#285;in por ke ni povu sendi tion al vi.</p>";
$esborrar_tots_prod = "Forvi&#349;u &#265;ion";


//PAGINA: FORMULARI
$compra_individual = "Individua a&#265;eto";
$soc_membre_KEA = "Mi estas membro de KEA";
$nom_complet = "Plena nomo";
$adreca = "Adreso";
$ciutat_i_cp = "Urbo kaj po&#349;t/kodo";
$pais = "Lando";
$correu = "ret-po&#349;to";
$dades_bancaries = "Bankaj datumoj";
$enviar_dades = "Sendu";
$netejar = "Forvi&#349;i";

//PAGINA: ARTICLES
$preu_daquest_llibre = "Prezo de tiu-&#265;i libro";
$nom_usuari = "Uzant-nomo";
$titol = "Titolo";
$comentari = "Komentario";
$publicar_comentari = "Publikigu la komenton";

//PAGINA: LOGIN
$introdueix_les_dades = "Skribu viajn datumojn";
$clau = "Pasvorto";
$entra = "Eniri";


//PAGINA: ADMINISTRACIO
$administracio = "Administrejo";
$admin_botiga = "Administrejo de la vendejo";
$eixir_sessio = "Foriri";
$afegir_poducte = "Aldoni novan produkton";
$modificar_producte = "Modifii produktojn";
$esborrar_producte = "Forvisxi produktojn";
$copies_seguretat = "Sekur-kopiojn";
$editar_missio = "Editi la anoncon";
$esborrar_comentaris = "Forvisxi komentojn";
$productes_pendents = "Produktojn atendante por sendi";
$historic_clients = "Historio de klientoj";
$categoria_productes = "Produkt-kategoriojn";






//PAGINA: AFEGINT NOU PRODUCTE
$afegint_producte = "Aldoni novan produkton";
$nom_del_producte = "Nomo de la produkto";
$autor_opcional = "Auxtoro (se gxi havus)";
$breu_descripcio = "Mallonga priskribo";
$pujar_imatge = "Imagxo";
$pujar_categoria = "Kategorio";
$preu_en_euros = "Prezo (en euxroj)";
$fitxer_pujat = "La produkton estis korekte publikigita!";


//PAGINA: MODIFICAR PRODUCTE
$descripcio_modificacions = "En cxi-tiu formularo oni povas modifii kaj korekti la datumojn de viaj produktoj. Se vi volas modifii imagxon, vi povas alsxuti la imagxo en la servilo kaj poste vi skribu sian nomon. Se vi volas modifii la kategorion de la produkto vi republikigu denove la produkton.";


//PAGINA: ESBORRAR PRODUCTE
$descripcio_esborrar = "Antaux cxio, vi estu certa pri kion vi faras, se vi forvisxas produkto vi perdas la informojn el la datumbazo de vi elektronika vendejo, cxu bone?";

//PAGINA: MISSIO DE LA WEB
$missio_web = "Anonco de la ttt-pagxo";
$desar_dades = "Savu informon";
$versio_actual = "Nuna versio";



//PAGINA: ESBORRAR COMENTARIS
$descripcio_esborracomentaris = "Antaux cxio, vi estu certa pri kion vi volas fari, cxar forvisxante komentojn cxi-tie vi malaperigos la datumojn en la datumbazo el la eletronika vendejo, cxu bone? Kaj memoru ke la komentoj plej novaj aperas malsube.";
$comentari_esborrat = "Vi korekte forvisxis la komenton!";



//PAGINA: PENDENTS D'ENVIAR
$descripcio_pendents = "Cxi-tie vi havas la produktojn ne-senditaj. Unu fojo vi sendas produkton, vi povas forlasxi gxin de tiu-cxi listo klakate la butonon 'Produkto sendita!'.";
$producte_enviat = "Produkto sendita!";



//PAGINA: HISTORIC CLIENTS
$descripcio_clients = "Tiu-cxi estas la listo de klientoj de via elektronika vendejo. Vi povas vidi pliajn informojn pri la klientoj klakante sur la dekstra imagxo. Ankaux vi povas vidi simplan liston Aquest &eacute;s el llistat de clients/clientes de la Libroservo. Pots veure m&eacute;s informaci&oacute; sobre els clients fent clic en la imatge de la dreta del nom del client. Tamb&eacute; pots veure que en des d'aquest simple llistat podem veure f&agrave;cilment quins clients s&oacute;n de la nostra associaci&oacute;";


//PAGINA: CATEGORIES
$categoria_esborrada = "La kategorio estis korekteforvisxita!";
$afegir_nova_categoria = "Aldoni novan kategorion";
$afegir_nova = "Aldoni novan";
$descripcio_categories = "En tiu-cxi fako vi povas aldoni novajn kategoriojn de produkoj por via elektronika vendejo aux ankaux vi povas forvisxi kategoriojn."; 
$llistat_categories = "Listo de la nunaj kategorioj";


?>






