<?php
//MENU PRINCIPAL
$botiga = "sklep internetowy";
$cistella = "koszyk";
$formulari = "formularz";


//PAGINA: BOTIGA
$categoria = "Kategoria";
$preu_total = "Razem";
$afegir_a_cistella = "Dodaj do koszyka";
$selecciona_una_categoria = "Wybierz kategorie...";
$productes = "Produkty";

$vols_afegir = "Czy chcesz dodac";
$a_la_cistella = "do koszyka?";


//PAGINA: ACXETAJXOJN
$producte = "Produkt";
$quants = "Ilosc";
$euro_la_unitat = "Cena w euro";
$quantitat_total_compra = "Sztuk";

//no fiqueu codi HTML perque va dins d'un script JAVASCRIPT i no es pot
$vols_esborrar = "Czy chcesz usunac wszystkie produkty z koszyka?";

$la_teua_cistella = "twój koszyk";
$descripcio_la_teua_cistella = "Po wybraniu róznych produktów, ukaza sie one w sklepie internetowym, mozesz dodac dowolna liczbe produktów, pózniej mozesz je z koszka usunac, co zostanie oznaczone czerwonym krzyzykiem po prawej stronie, jesli chcesz wyslac zamówienie na artkuly znajdujace sie w twoim koszyku, przejdz do formularza i go wypelnij, abysmy mogli zrealizowac przesylke.";

$esborrar_tots_prod = "Usun wszystkie produkty";


//PAGINA: FORMULARI  
$compra_individual = "zakup indywidualny";
$soc_membre_KEA = "jestem czlonkiem KEA";
$nom_complet = "Imie i nazwisko";
$adreca = "Adres";
$ciutat_i_cp = "Miejscowosc i kod";
$pais = "Kraj";
$correu = "E-mail";
$dades_bancaries = "Numer kota";
$enviar_dades = "Wyslij";
$netejar = "Usun";

//PAGINA: ARTICLES 
$preu_daquest_llibre = "Cena ksiazki";
$nom_usuari = "Nazwa uzytkownika";
$titol = "Tytul";
$comentari = "Komentarz";
$publicar_comentari = "Wyslij komentarz";

//PAGINA: LOGIN
$introdueix_les_dades = "Introduinsky viajn datinksi";
$clau = "Contrasenyiski";
$entra = "Enirinski";


//PAGINA: ADMINISTRACIO
$administracio = "Administrinsky";
$admin_botiga = "Administrinsky de la botiguinsky";
$eixir_sessio = "Eixinky";
$afegir_poducte = "Aldoninsky novan produktisnky";
$modificar_producte = "Modifinsky productinsky";
$esborrar_producte = "Esborrjy productisnky";
$copies_seguretat = "C&ograve;ynsky de segury";
$editar_missio = "Editynsky missi&oynsky;";
$esborrar_comentaris = "Esborry comentej";
$productes_pendents = "Productynks pendyn d'envynsky";
$historic_clients = "Hist&ograysy dj clienty";
$categoria_productes = "Categoriynsky dj produktynsky";





//PAGINA: AFEGINT NOU PRODUCTE
$afegint_producte = "Afegint novinsky produkinsky";
$afegint_producte = "Afeginty  productinsky";
$nom_del_producte = "Nomy produkti";
$autor_opcional = "Autorinsky (opcionalinksy)";
$breu_descripcio = "Mallonginski priskrib";
$pujar_imatge = "Imaginsky";
$pujar_categoria = "Kategorinsky";
$preu_en_euros = "Prey (euro)";
$fitxer_pujat = "El fitxerinsky s'ha pujat correctamentinsky!";


//PAGINA: MODIFICAR PRODUCTE
$descripcio_modificacions = "polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski.";


//PAGINA: ESBORRAR PRODUCTE
$descripcio_esborrar = "polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski";

//PAGINA: MISSIO DE LA WEB
$missio_web = "Missi&insky webinsky";
$desar_dades = "Desarinsky informinsky";
$versio_actual = "Versinsky actualisnky";


//PAGINA: ESBORRAR COMENTARIS
$descripcio_esborracomentaris = "polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski.";
$comentari_esborrat = "El comentarinsky ha segynsky cornsky!";


//PAGINA: PENDENTS D'ENVIAR
$descripcio_pendents = "polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polskipolski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski.";
$producte_enviat = "Prodke enviinsky!";

//PAGINA: HISTORIC CLIENTS
$descripcio_clients = "polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski.";


//PAGINA: CATEGORIES
$categoria_esborrada = "La kategory yyyyy yyy yyy yy y!";
$afegir_nova_categoria = "Afeginsky nove categorinsky";
$afegir_nova = "Afeginsky novy";
$descripcio_categories = "polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski, polski,."; 
$llistat_categories = "Llistinsky de kategorisnky akutyensky";

?>








