<?php

$botiga = "botiga";
$cistella = "cistella";
$formulari = "formulari";


$categoria = "Categoria";
$preu_total = "Preu total";
$afegir_a_cistella = "Afegir a la cistella";
$selecciona_una_categoria = "Selecciona una categoria...";
$productes = "Productes";

$vols_afegir = "Vols afegir";
$a_la_cistella = "a la cistella";

$producte = "Producte";
$quants = "Quants";
$euro_la_unitat = "&euro; la unitat";
$quantitat_total_compra = "Quantitat total de la compra";

//no fiqueu codi HTML perque va dins d'un script JAVASCRIPT i no es pot
$vols_esborrar = "Vols esborrar tots els productes de la cistella?";

$la_teua_cistella = "La teua cistella";
$descripcio_la_teua_cistella = "A mesura que vagis triant productes diversos en la part de la botiga aniran apareixent aqu&iacute; en el llistat de productes de la cistella. Pots afegir tants productes com vulguis i tamb&eacute; pots esborrar productes de la cistella fent clic a la creueta roja.</p> <p>Si despr&eacute; ja vols fer la teua comanda, fes clic en 'formulari' i ompleix totes les dades neces&agrave;ries i t'enviarem a casa els productes.</p>";
$esborrar_tots_prod = "Esborrar tots els productes";

//PAGINA: FORMULARI
$compra_individual = "Compra individual";
$soc_membre_KEA = "S&oacute;c membre de KEA";
$nom_complet = "Nom complet";
$adreca = "Adre&ccedil;a";
$ciutat_i_cp = "Ciutat i CP";
$pais = "Pa&iacute;s";
$correu = "Correu";
$dades_bancaries = "Dades banc&agrave;ries";
$enviar_dades = "Enviar dades";
$netejar = "Netejar";
$apunt_sobre_el_pagament = "* Introdueix <b>totes les dades del teu banc</b> (entitat, codi i compte) Et garantim la m&agrave;xima seguretat i privacitat de dades en la teua compra. Una vegada facis la petici&oacute; carregarem la quantitat de la teua compra al teu banc deixant una descripci&oacute; clara de l'operaci&oacute; signada amb el nom de la nostra associaci&oacute;";

//PAGINA: ARTICLES
$preu_daquest_llibre = "Preu d'aquest llibre";
$nom_usuari = "Nom d'usuari";
$titol = "T&iacute;tol";
$comentari = "Comentari";
$publicar_comentari = "Publica el komentari";


//PAGINA: LOGIN
$introdueix_les_dades = "Introdueix les teues dades";
$clau = "Contrasenya";
$entra = "Entrar";

//PAGINA: ADMINISTRACIO
$administracio = "Administració";
$admin_botiga = "Administració de la botiga";
$eixir_sessio = "Eixir";
$afegir_poducte = "Afegir nou producte";
$modificar_producte = "Modificar productes";
$esborrar_producte = "Esborrar productes";
$copies_seguretat = "C&ograve;pies de seguretat";
$editar_missio = "Editar la missi&oacute;";
$esborrar_comentaris = "Esborrar comentaris";
$productes_pendents = "Productes pendents d'enviar";
$historic_clients = "Hist&ograve;ric de clients";
$categoria_productes = "Categories de productes";



//PAGINA: AFEGINT NOU PRODUCTE
$afegint_producte = "Afegint un nou producte";
$nom_del_producte = "Nom del producte";
$autor_opcional = "Autor (camp opcional)";
$breu_descripcio = "Breu descripció";
$pujar_imatge = "Imatge";
$pujar_categoria = "Categoria";
$preu_en_euros = "Preu (en euros)";
$fitxer_pujat = "El fitxer ha segut publicat correctament!";


//PAGINA: MODIFICAR PRODUCTE
$descripcio_modificacions = "Des d'aquest formulari pots modificar i corregir dades dels productes publicats a la botiga. Si vols modificar una imatge, pots pujar-la al servidor i despr&eacute;s escriure en el camp el nou nom. Si vols modificar la categoria es millor esborrar el producte i crear-lo novament.";


//PAGINA: ESBORRAR PRODUCTE
$descripcio_esborrar = "Abans de res, estigues segur del que vols fer, perqu&egrave; al esborrar un producte desapareixer&agrave; totalment de la base de dades de la botiga virtual, d'acord?";


//PAGINA: MISSIO DE LA WEB
$missio_web = "Missió de la web";
$desar_dades = "Desar dades";
$versio_actual = "Versió actual";


//PAGINA: ESBORRAR COMENTARIS
$descripcio_esborracomentaris = "Abans de res, estigues segur del que vols fer, perqu&egrave; al esborrar un comentari desapareixer&agrave; totalment de la base de dades de la botiga virtual, d'acord? Et recordem que al llistat, els comentaris m&eacute;s nous apareixen a dalt.";
$comentari_esborrat = "El comentari ha segut esborrat correctament!";


//PAGINA: PENDENTS D'ENVIAR
$descripcio_pendents = "Aquest és el llistat dels productes que encara no han segut enviats. Envieu-los i una volta feu l'enviament els podeu donar de baixa en aquesta llista fent clic en el bot&oacute; 'producte enviat!'.";
$producte_enviat = "Producte enviat!";


//PAGINA: HISTORIC CLIENTS
$descripcio_clients = "Aquest &eacute;s el llistat de clients/clientes de la Libroservo. Pots veure m&eacute;s informaci&oacute; sobre els clients fent clic en la imatge de la dreta del nom del client. Tamb&eacute; pots veure que en des d'aquest simple llistat podem veure f&agrave;cilment quins clients s&oacute;n de la nostra associaci&oacute;";


//PAGINA: CATEGORIES
$categoria_esborrada = "La categoria ha segut esborrada correctament!";
$afegir_nova_categoria = "Afegir nova categoria";
$afegir_nova = "Afegir nova";
$descripcio_categories = "En aquest apartat pots afegir una nova categoria de productes per la botiga virtual o tamb&eacute; esborrar alguna categoria actual."; 
$llistat_categories = "Llistat de categories actuals";

?>
